version: "3"

services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring

  server:
    build:
      context: ../server
    container_name: devops_server
    ports:
      - "8000:8000"
    expose:
      - "8000"
    networks:
      - monitoring

networks:
  monitoring:
